### ISSUE TITLE
annotations.js contains parent name called `comments`

### ISSUE THREAD

**Issue by XmlmXmlmX** [pattern-lab/starterkit-mustache-base#1]
Why contains the _JSON_ file a parent name called `comments`? In the [Patternlab docs](http://patternlab.io/docs/pattern-adding-annotations.html), there is nothing like that. And it doesn't work.

**Comment by dmolsen** [comment]
Thanks for the heads up. I'll look into it.

**Comment by davejtoews** [comment]
If you remove the parent `comments` node, the annotations won't be compiled into `public/annotations/annotations.js`. Additionally if you remove the parent `comments` from the compiled file you get a js error. "TypeError: undefined is not an object (evaluating \`comments.comments.length\`". So, it appears `comments` is necessary.

However, like @XmlmXmlmX, I can't actually get annotations to work, regardless of the formatting.

**Comment by bmuenzenmeyer** [comment]
this was a vestigial syntax that we've attempted to support for backwards compatibility within Pattern Lab Node. Last I checked an annotations file like [this one](https://github.com/pattern-lab/starterkit-mustache-demo/blob/develop/dist/_annotations/annotations.js) or yaml should work.
